# Generated by Django 2.1.1 on 2018-10-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180828_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='oven0DeviceTable',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('currState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='当前状态')),
                ('nextState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='下一步状态')),
                ('IP', models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址')),
                ('PortNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口号')),
                ('Addr', models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址')),
                ('protocolVersion', models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号')),
                ('ovenPlanID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ovenPlanTable', verbose_name='炉子测试方案ID')),
            ],
        ),
        migrations.CreateModel(
            name='oven1DeviceTable',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('currState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='当前状态')),
                ('nextState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='下一步状态')),
                ('IP', models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址')),
                ('PortNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口号')),
                ('Addr', models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址')),
                ('protocolVersion', models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号')),
                ('ovenPlanID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ovenPlanTable', verbose_name='炉子测试方案ID')),
            ],
        ),
        migrations.CreateModel(
            name='oven2DeviceTable',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('currState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='当前状态')),
                ('nextState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='下一步状态')),
                ('IP', models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址')),
                ('PortNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口号')),
                ('Addr', models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址')),
                ('protocolVersion', models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号')),
                ('ovenPlanID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ovenPlanTable', verbose_name='炉子测试方案ID')),
            ],
        ),
        migrations.CreateModel(
            name='oven3DeviceTable',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('currState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='当前状态')),
                ('nextState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='下一步状态')),
                ('IP', models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址')),
                ('PortNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口号')),
                ('Addr', models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址')),
                ('protocolVersion', models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号')),
                ('ovenPlanID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ovenPlanTable', verbose_name='炉子测试方案ID')),
            ],
        ),
        migrations.CreateModel(
            name='voltDeviceTable',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('IP', models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址')),
                ('PortNum', models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号')),
                ('Addr', models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址')),
                ('totalChnNum', models.IntegerField(blank=True, default=1, null=True, verbose_name='总通道数')),
                ('protocolVersion', models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号')),
            ],
        ),
        migrations.RemoveField(
            model_name='ovendevicetable',
            name='ovenPlanID',
        ),
        migrations.RemoveField(
            model_name='bigtestinfotable',
            name='ovenID',
        ),
        migrations.RemoveField(
            model_name='bigtestinfotable',
            name='ovenPlanID',
        ),
        migrations.RemoveField(
            model_name='celldevicetable',
            name='mT0ID',
        ),
        migrations.RemoveField(
            model_name='celldevicetable',
            name='mT1ID',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='T0',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='T1',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='T2',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='T3',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='T4',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='sT0',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='sT1',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='sT2',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='sT3',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='sT4',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='tT0',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='tT1',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='tT2',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='tT3',
        ),
        migrations.RemoveField(
            model_name='celltesthistorydatatable',
            name='tT4',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='T0',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='T1',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='T2',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='T3',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='T4',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='sT0',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='sT1',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='sT2',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='sT3',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='sT4',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='tT0',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='tT1',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='tT2',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='tT3',
        ),
        migrations.RemoveField(
            model_name='celltestrealdatatable',
            name='tT4',
        ),
        migrations.AddField(
            model_name='airdevicetable',
            name='fullScale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='满量程值'),
        ),
        migrations.AddField(
            model_name='celldevicetable',
            name='mTmID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.wdjDeviceTable', verbose_name='温度计ID'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tc0',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点0'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tc1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点1'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tc2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点2'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tc3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点3'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm0',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点0'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点1'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm10',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点10'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm11',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点11'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm12',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点12'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm13',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点13'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm14',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点14'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm15',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点15'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm16',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点16'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm17',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点17'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm18',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点18'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm19',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点19'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点2'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点3'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点4'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm5',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点5'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm6',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点6'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm7',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点7'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点8'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Tm9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点9'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm0',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点0'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点1'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm10',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点10'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm11',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点11'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm12',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点12'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm13',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点13'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm14',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点14'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm15',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点15'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm16',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点16'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm17',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点17'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm18',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点18'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm19',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点19'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点2'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点3'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点4'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm5',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点5'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm6',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点6'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm7',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点7'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点8'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='Vm9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点9'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='sTc0',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='sTc1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='sTc2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='sTc3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTc0',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTc1',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTc2',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTc3',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm0',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm1',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm10',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T10数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm11',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T11数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm12',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T12数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm13',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T13数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm14',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T14数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm15',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T15数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm16',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T16数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm17',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T17数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm18',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T18数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm19',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T19数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm2',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm3',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm4',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T4数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm5',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T5数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm6',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T6数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm7',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T7数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm8',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T8数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tTm9',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T9数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm0',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V0数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm1',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V1数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm10',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V10数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm11',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V11数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm12',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V12数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm13',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V13数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm14',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V14数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm15',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V15数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm16',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V16数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm17',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V17数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm18',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V18数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm19',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V19数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm2',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V2数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm3',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V3数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm4',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V4数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm5',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V5数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm6',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V6数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm7',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V7数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm8',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V8数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltesthistorydatatable',
            name='tVm9',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V9数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tc0',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点0'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tc1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点1'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tc2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点2'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tc3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度控制点3'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm0',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点0'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点1'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm10',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点10'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm11',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点11'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm12',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点12'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm13',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点13'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm14',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点14'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm15',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点15'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm16',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点16'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm17',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点17'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm18',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点18'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm19',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点19'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点2'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点3'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点4'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm5',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点5'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm6',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点6'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm7',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点7'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点8'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Tm9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='温度监测点9'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm0',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点0'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm1',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点1'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm10',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点10'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm11',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点11'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm12',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点12'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm13',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点13'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm14',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点14'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm15',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点15'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm16',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点16'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm17',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点17'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm18',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点18'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm19',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点19'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm2',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点2'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm3',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点3'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm4',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点4'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm5',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点5'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm6',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点6'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm7',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点7'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm8',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点8'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='Vm9',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True, verbose_name='电压监测点9'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='sTc0',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='sTc1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='sTc2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='sTc3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='通讯状态'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTc0',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTc1',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTc2',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTc3',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm0',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm1',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm10',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T10数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm11',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T11数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm12',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T12数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm13',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T13数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm14',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T14数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm15',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T15数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm16',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T16数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm17',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T17数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm18',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T18数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm19',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T19数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm2',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm3',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm4',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T4数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm5',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T5数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm6',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T6数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm7',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T7数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm8',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T8数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tTm9',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='T9数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm0',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V0数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm1',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V1数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm10',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V10数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm11',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V11数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm12',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V12数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm13',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V13数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm14',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V14数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm15',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V15数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm16',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V16数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm17',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V17数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm18',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V18数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm19',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V19数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm2',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V2数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm3',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V3数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm4',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V4数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm5',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V5数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm6',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V6数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm7',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V7数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm8',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V8数据修改时间'),
        ),
        migrations.AddField(
            model_name='celltestrealdatatable',
            name='tVm9',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='V9数据修改时间'),
        ),
        migrations.AddField(
            model_name='ch4devicetable',
            name='fullScale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='满量程值'),
        ),
        migrations.AddField(
            model_name='co2devicetable',
            name='fullScale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='满量程值'),
        ),
        migrations.AddField(
            model_name='h2devicetable',
            name='fullScale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='满量程值'),
        ),
        migrations.AddField(
            model_name='h2odevicetable',
            name='fullScale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='满量程值'),
        ),
        migrations.AddField(
            model_name='n2devicetable',
            name='fullScale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='满量程值'),
        ),
        migrations.AddField(
            model_name='wdjdevicetable',
            name='protocolVersion',
            field=models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号'),
        ),
        migrations.AddField(
            model_name='wdjdevicetable',
            name='totalChnNum',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='总通道数'),
        ),
        migrations.AlterField(
            model_name='airdevicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=32, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='airdevicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='airdevicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='airdevicetable',
            name='currState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当前设定流量'),
        ),
        migrations.AlterField(
            model_name='airdevicetable',
            name='nextState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='下一步设定流量'),
        ),
        migrations.AlterField(
            model_name='bigtestinfotable',
            name='wdjID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.wdjDeviceTable', verbose_name='wdj0ID'),
        ),
        migrations.AlterField(
            model_name='boxdevicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='boxdevicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='cellID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='电池/电堆编号'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qAIR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='空气流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qCH4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='CH4流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qCO2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='CO2流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qH2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='H2流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qH2O',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='水流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qN2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='N2流量'),
        ),
        migrations.AlterField(
            model_name='ch4devicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=32, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='ch4devicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='ch4devicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='ch4devicetable',
            name='currState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当前设定流量'),
        ),
        migrations.AlterField(
            model_name='ch4devicetable',
            name='nextState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='下一步设定流量'),
        ),
        migrations.AlterField(
            model_name='co2devicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=32, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='co2devicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='co2devicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='co2devicetable',
            name='currState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当前设定流量'),
        ),
        migrations.AlterField(
            model_name='co2devicetable',
            name='nextState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='下一步设定流量'),
        ),
        migrations.AlterField(
            model_name='h2devicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=32, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='h2devicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='h2devicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='h2devicetable',
            name='currState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当前设定流量'),
        ),
        migrations.AlterField(
            model_name='h2devicetable',
            name='nextState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='下一步设定流量'),
        ),
        migrations.AlterField(
            model_name='h2odevicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=32, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='h2odevicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='h2odevicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='h2odevicetable',
            name='currState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当前设定流量'),
        ),
        migrations.AlterField(
            model_name='h2odevicetable',
            name='nextState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='下一步设定流量'),
        ),
        migrations.AlterField(
            model_name='n2devicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=32, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='n2devicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='n2devicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='n2devicetable',
            name='currState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当前设定流量'),
        ),
        migrations.AlterField(
            model_name='n2devicetable',
            name='nextState',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='下一步设定流量'),
        ),
        migrations.AlterField(
            model_name='wdjdevicetable',
            name='Addr',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址'),
        ),
        migrations.AlterField(
            model_name='wdjdevicetable',
            name='IP',
            field=models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='wdjdevicetable',
            name='PortNum',
            field=models.IntegerField(blank=True, default=20001, null=True, verbose_name='端口号'),
        ),
        migrations.DeleteModel(
            name='ovenDeviceTable',
        ),
        migrations.AddField(
            model_name='bigtestinfotable',
            name='oven0ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven0DeviceTable', verbose_name='ovenID'),
        ),
        migrations.AddField(
            model_name='bigtestinfotable',
            name='oven1ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven1DeviceTable', verbose_name='ovenID'),
        ),
        migrations.AddField(
            model_name='bigtestinfotable',
            name='oven2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven2DeviceTable', verbose_name='ovenID'),
        ),
        migrations.AddField(
            model_name='bigtestinfotable',
            name='oven3ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven3DeviceTable', verbose_name='ovenID'),
        ),
        migrations.AddField(
            model_name='bigtestinfotable',
            name='voltID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.voltDeviceTable', verbose_name='volt0ID'),
        ),
        migrations.AddField(
            model_name='celldevicetable',
            name='mTc0ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven0DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AddField(
            model_name='celldevicetable',
            name='mTc1ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven1DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AddField(
            model_name='celldevicetable',
            name='mTc2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven2DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AddField(
            model_name='celldevicetable',
            name='mTc3ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.oven3DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AddField(
            model_name='celldevicetable',
            name='mVmID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.voltDeviceTable', verbose_name='电压表ID'),
        ),
    ]
