# Generated by Django 2.1.1 on 2018-10-03 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20181003_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc0ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_oven', to='apps.oven0DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc1ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_oven', to='apps.oven0DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_oven', to='apps.oven0DeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc3ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_oven', to='apps.oven0DeviceTable', verbose_name='温控器ID'),
        ),
    ]
