# Generated by Django 2.1.1 on 2018-10-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20181003_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='ovenDeviceTable',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='设备编号')),
                ('currState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='当前状态')),
                ('nextState', models.CharField(choices=[('stop', '停止'), ('pause', '暂停'), ('start', '启动'), ('resume', '继续')], default='stop', max_length=10, verbose_name='下一步状态')),
                ('IP', models.GenericIPAddressField(blank=True, default='192.168.0.3', null=True, verbose_name='IP地址')),
                ('PortNum', models.IntegerField(blank=True, default=0, null=True, verbose_name='端口号')),
                ('Addr', models.IntegerField(blank=True, default=1, null=True, verbose_name='485地址')),
                ('protocolVersion', models.CharField(blank=True, default='7', max_length=2, null=True, verbose_name='宇电表头协议版本号')),
                ('ovenPlanID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ovenPlanTable', verbose_name='炉子测试方案ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='oven0devicetable',
            name='ovenPlanID',
        ),
        migrations.RemoveField(
            model_name='oven1devicetable',
            name='ovenPlanID',
        ),
        migrations.RemoveField(
            model_name='oven2devicetable',
            name='ovenPlanID',
        ),
        migrations.RemoveField(
            model_name='oven3devicetable',
            name='ovenPlanID',
        ),
        migrations.AlterField(
            model_name='bigtestinfotable',
            name='oven0ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstoven', to='apps.ovenDeviceTable', verbose_name='ovenID'),
        ),
        migrations.AlterField(
            model_name='bigtestinfotable',
            name='oven1ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondoven', to='apps.ovenDeviceTable', verbose_name='ovenID'),
        ),
        migrations.AlterField(
            model_name='bigtestinfotable',
            name='oven2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdoven', to='apps.ovenDeviceTable', verbose_name='ovenID'),
        ),
        migrations.AlterField(
            model_name='bigtestinfotable',
            name='oven3ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourthoven', to='apps.ovenDeviceTable', verbose_name='ovenID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc0ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_oven', to='apps.ovenDeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc1ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_oven', to='apps.ovenDeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc2ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_oven', to='apps.ovenDeviceTable', verbose_name='温控器ID'),
        ),
        migrations.AlterField(
            model_name='celldevicetable',
            name='mTc3ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_oven', to='apps.ovenDeviceTable', verbose_name='温控器ID'),
        ),
        migrations.DeleteModel(
            name='oven0DeviceTable',
        ),
        migrations.DeleteModel(
            name='oven1DeviceTable',
        ),
        migrations.DeleteModel(
            name='oven2DeviceTable',
        ),
        migrations.DeleteModel(
            name='oven3DeviceTable',
        ),
    ]
