# Generated by Django 2.1.1 on 2018-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20181003_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltdevicetable',
            name='totalChnNum',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='总通道数'),
        ),
        migrations.AlterField(
            model_name='wdjdevicetable',
            name='totalChnNum',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='总通道数'),
        ),
    ]
