# Generated by Django 2.1.1 on 2018-10-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20181005_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='celldata_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='电池数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tAIR',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AIR数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tCH4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CH4数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tCO2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CO2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tH2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='H2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tH2O',
            field=models.DateTimeField(blank=True, null=True, verbose_name='H2O数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tN2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='N2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTc0',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTc1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTc2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTc3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm0',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm10',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T10数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm11',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T11数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm12',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T12数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm13',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T13数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm14',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T14数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm15',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T15数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm16',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T16数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm17',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T17数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm18',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T18数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm19',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T19数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T4数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm5',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T5数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm6',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T6数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm7',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T7数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm8',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T8数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tTm9',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T9数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm0',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V0数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V1数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm10',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V10数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm11',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V11数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm12',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V12数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm13',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V13数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm14',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V14数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm15',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V15数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm16',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V16数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm17',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V17数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm18',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V18数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm19',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V19数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V3数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V4数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm5',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V5数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm6',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V6数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm7',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V7数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm8',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V8数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltesthistorydatatable',
            name='tVm9',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V9数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='celldata_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='电池数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tAIR',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AIR数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tCH4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CH4数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tCO2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CO2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tH2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='H2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tH2O',
            field=models.DateTimeField(blank=True, null=True, verbose_name='H2O数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tN2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='N2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTc0',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTc1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTc2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTc3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm0',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T0数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T1数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm10',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T10数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm11',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T11数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm12',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T12数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm13',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T13数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm14',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T14数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm15',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T15数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm16',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T16数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm17',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T17数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm18',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T18数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm19',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T19数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T3数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T4数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm5',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T5数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm6',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T6数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm7',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T7数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm8',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T8数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tTm9',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T9数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm0',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V0数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V1数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm10',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V10数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm11',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V11数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm12',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V12数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm13',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V13数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm14',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V14数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm15',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V15数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm16',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V16数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm17',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V17数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm18',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V18数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm19',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V19数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V2数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V3数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm4',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V4数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm5',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V5数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm6',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V6数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm7',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V7数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm8',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V8数据修改时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tVm9',
            field=models.DateTimeField(blank=True, null=True, verbose_name='V9数据修改时间'),
        ),
    ]
