# Generated by Django 2.1.1 on 2018-10-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20181006_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='T',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前温度'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tc0',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度控制点0'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tc1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度控制点1'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tc2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度控制点2'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tc3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度控制点3'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm0',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点0'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点1'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm10',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点10'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm11',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点11'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm12',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点12'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm13',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点13'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm14',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点14'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm15',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点15'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm16',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点16'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm17',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点17'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm18',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点18'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm19',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点19'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点2'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点3'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点4'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点5'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm6',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点6'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm7',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点7'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm8',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点8'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Tm9',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='温度监测点9'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm0',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点0'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点1'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm10',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点10'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm11',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点11'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm12',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点12'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm13',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点13'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm14',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点14'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm15',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点15'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm16',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点16'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm17',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点17'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm18',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点18'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm19',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点19'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点2'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点3'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点4'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点5'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm6',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点6'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm7',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点7'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm8',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点8'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='Vm9',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='电压监测点9'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='chMasterSlaveFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='通道主从标志'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='chState',
            field=models.IntegerField(blank=True, null=True, verbose_name='通道状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='chStateCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='通道异常代码'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='chnNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='通道号'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='conState',
            field=models.IntegerField(blank=True, null=True, verbose_name='联机状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='detailDataFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否有明细数据'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='i',
            field=models.IntegerField(blank=True, null=True, verbose_name='实时电流'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='k',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前过程号'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='工作模式'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='n',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前工步号'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='overOutDataFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否有数据溢出'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='powerDownFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否有设备断电'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='q',
            field=models.IntegerField(blank=True, null=True, verbose_name='实时容量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qA',
            field=models.IntegerField(blank=True, null=True, verbose_name='累计容量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qAIR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='空气流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qCH4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CH4流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qCO2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CO2流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qH2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='H2流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qH2O',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='水流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='qN2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='N2流量'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='r',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前内阻'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='resultDataFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='是否有结果数据'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sAIR',
            field=models.IntegerField(blank=True, null=True, verbose_name='AIR通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sCH4',
            field=models.IntegerField(blank=True, null=True, verbose_name='CH4通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sCO2',
            field=models.IntegerField(blank=True, null=True, verbose_name='CO2通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sH2',
            field=models.IntegerField(blank=True, null=True, verbose_name='H2通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sH2O',
            field=models.IntegerField(blank=True, null=True, verbose_name='H2O通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sN2',
            field=models.IntegerField(blank=True, null=True, verbose_name='N2通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sTc0',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tc0通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sTc1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tc1通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sTc2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tc2通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='sTc3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tc3通讯状态'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='ta',
            field=models.IntegerField(blank=True, null=True, verbose_name='本工步累计时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='tc',
            field=models.IntegerField(blank=True, null=True, verbose_name='本工步已工作时间'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='totalStepN',
            field=models.IntegerField(blank=True, null=True, verbose_name='总工步数'),
        ),
        migrations.AlterField(
            model_name='celltestrealdatatable',
            name='u',
            field=models.IntegerField(blank=True, null=True, verbose_name='实时电压'),
        ),
    ]
